This semi colon causes errors
SyntaxError: Unexpected token ;
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\UserName\Desktop\steambot\MyBot.js:63:16)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
 2016-10-09T14:01:52.575Z - info: tumblemusic/chatBot.js: logging output to: bot.username.log
2016-10-09T14:01:52.591Z - info: tumblemusic/chatBot.js: using sentryFile bot.username.sentry
2016-10-09T14:01:52.601Z - debug: tumblemusic/chatBot.js: Initializing webserver
C:\Users\UserName\Desktop\steambot\example-config-triggers.js:131
                        forecastMetric: false;
                                                        ^